<?php
declare(strict_types=1);
require_once __DIR__.'/../../../backend/conexion.php'; require_once __DIR__.'/../../../backend/security.php';
requireAdmin();
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0'); header('Pragma: no-cache');
$rut=normalizeRut((string)($_GET['rut']??'')); if($rut===''||mb_strlen($rut)>12){http_response_code(400);exit('RUT no indicado.');}
$stmt=$conn->prepare('SELECT oc.*,u.username FROM operador_cargador oc LEFT JOIN usuarios u ON oc.usuario_id=u.id WHERE oc.eliminado_at IS NULL AND oc.rut=? ORDER BY oc.fecha_registro DESC');$stmt->bind_param('s',$rut);$stmt->execute();$cargadores=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);
$stmt=$conn->prepare('SELECT o.*,u.username FROM operador o LEFT JOIN usuarios u ON o.usuario_id=u.id WHERE o.eliminado_at IS NULL AND o.rut=? ORDER BY o.fecha_registro DESC');$stmt->bind_param('s',$rut);$stmt->execute();$operadores=$stmt->get_result()->fetch_all(MYSQLI_ASSOC);
if(!$cargadores&&!$operadores){http_response_code(404);exit('No se encontró el RUT.');}
audit($conn,(int)$_SESSION['usuario_id'],'IMPRIMIR_RUT','',null,'RUT '.$rut);
function fila(string $e1,mixed $v):void{echo '<tr><th>'.e($e1).'</th><td>'.e($v).'</td></tr>';}
function n(mixed $v):string{return number_format((float)$v,2,',','.').' L';}
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Registro RUT <?=e($rut)?></title><link rel="stylesheet" href="../../../css/programa/imprimir_registro.css"><script src="../../../js/programa/imprimir.js" defer></script></head><body><div class="hoja"><div class="cabecera"><div><h1>Control de Combustible <?=e(appName())?></h1><p>Detalle completo por RUT</p></div><div class="rut-principal">RUT: <strong><?=e($rut)?></strong></div></div><?php if($cargadores): ?><section><h2>Operador Cargador</h2><p><strong>Total acumulado: <?=n(array_sum(array_column($cargadores,'litros')))?></strong></p><?php foreach($cargadores as $r): ?><table><?php fila('Usuario que registró',$r['username']??'Sin usuario');fila('Nombres',$r['nombres']);fila('Apellido Paterno',$r['apellido_paterno']);fila('Apellido Materno',$r['apellido_materno']);fila('RUT',$r['rut']);fila('Turno',$r['turno']);fila('Código',$r['codigo']);fila('Ubicación GPS',$r['ubicacion']);fila('Patente',$r['patente']);fila('Horómetro',$r['horometro']);fila('Litros',n($r['litros']));fila('Remanente',n($r['remanente']));fila('Observación',$r['observacion']);fila('Fecha de registro',$r['fecha_registro']); ?></table><hr><?php endforeach;?></section><?php endif;?><?php if($operadores): ?><section><h2>Operador</h2><p><strong>Total acumulado: <?=n(array_sum(array_column($operadores,'litros')))?></strong></p><?php foreach($operadores as $r): ?><table><?php fila('Usuario que registró',$r['username']??'Sin usuario');fila('Nombres',$r['nombres']);fila('Apellido Paterno',$r['apellido_paterno']);fila('Apellido Materno',$r['apellido_materno']);fila('RUT',$r['rut']);fila('Turno',$r['turno']);fila('Ubicación GPS',$r['ubicacion']);fila('Código Maquinaria',$r['codigo_maquinaria']);fila('Patente',$r['patente']);fila('Equipo',$r['equipo']);fila('Horómetro',$r['horometro']);fila('Kilómetro',$r['kilometro']);fila('Litros',n($r['litros']));fila('Consumo',$r['consumo']);fila('Observación',$r['observacion']);fila('Fecha de registro',$r['fecha_registro']); ?></table><hr><?php endforeach;?></section><?php endif;?><div class="acciones-impresion"><button type="button" id="btnImprimir">🖨️ Imprimir</button><button type="button" class="secundario" id="btnCerrar">Cerrar</button></div></div></body></html>
